### ISSUE TITLE
human shows '0 seconds ago' in Firefox

### ISSUE THREAD

**Issue by tuxillo** [bahamas10/human#1]
Hi,

Site: https://us-east.manta.joyent.com/Joyent_Dev/public/SmartOS/smartos.html#20150612T210440Z

In Firefox and IE it shows : 0 seconds ago.
In Chrome it works.

Cheers,
Antonio Huete

**Comment by bahamas10** [comment]
this was fixed with https://github.com/bahamas10/smartos-changelog/commit/27fc955fb96d8a56df0f1a9775d932155c7d69d1 thanks!
